### ISSUE TITLE
Create a comprehensive user's guide

### ISSUE THREAD

**Issue by rsdunlapiv** [cupid-ide/cupid#24]
The tutorial is a good start:
https://earthsystemcog.org/projects/cupid/tutorial

**Comment by murphysj** [comment]
What software are you going to use for this? There has been a lot of internal discussion about what is maintainable by the larger group. OCGIS is now using sphinx in the code and readthedocs to display it. C will not like some new system AND will require the guide to be version specific.

**Comment by rsdunlapiv** [comment]
The user guide is underway and will also use readthedocs.  It does allow version-specific docs.
http://cupid.readthedocs.org/
