### ISSUE TITLE
Create non-NUOPC to NUOPC code conversion guide

### ISSUE THREAD

**Issue by murphysj** [cupid-ide/cupid#30]
WHO: Cecelia

Ensure that there is a documentation or wizard step-by-step guide for a user who wants to create a NUOPC code out of their own non-NUOPC code.

**Comment by rsdunlapiv** [comment]
This has been done:
http://www.earthsystemmodeling.org/nuopc/docs/buildnuopccomp/

Cecelia requested we move this into the Protex/LaTeX doc system used in ESMF and that conversion is underway now.

**Comment by rsdunlapiv** [comment]
This was moved over to Protex/Latex and is being built with the rest of the docs:
http://www.earthsystemmodeling.org/esmf_releases/non_public/ESMF_7_0_0/NUOPC_howtodoc/
